Detect when PyProxies are used with the GIL released and raise an error (#3719)
Resolves #3717.

Before:

```js
$ tstate = pyodide._module._PyEval_SaveThread()
$ pyodide.globals.get("x")
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
RuntimeError: memory access out of bounds
```

After:

```js
$ tstate = pyodide._module._PyEval_SaveThread()
$ pyodide.globals.get("x")
Uncaught NoGilError: Attempted to use PyProxy when Python GIL not held
```