FIX Escape nbsp in console.html (#3558)
Resolves https://github.com/pyodide/pyodide/issues/3337

In Firefox if one writes anything with spaces then tries to copy-paste the input to a standard Python REPL, one gets,

SyntaxError: invalid non-printable character U+00A0

this is because spaces are replaced by the non-breaking space character.

This patch replaces non-breaking space characters with normal space characters in the repl.