MAINT print more details when test fails due to leaked proxy
This should make debugging these failures way easier.

Example output:

```
conftest.py:222: in pytest_runtest_call
    yield from extra_checks_test_wrapper(
conftest.py:268: in extra_checks_test_wrapper
    assert (delta_proxies, delta_keys) == (0, 0) or delta_keys < 0
E   assert ((2, 0) == (0, 0)
E     At index 0 diff: 2 != 0
E     Use -v to get more diff or 0 < 0)
------------------------------------------------------------------------------------------ Captured stdout setup -------------------------------------------------------------------------------------------
Spawning webserver at http://127.0.0.1:50225 (see logs in /tmp/tmphjwsjodd/http-server.log)
------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
leaked proxies:
tuple (1, 2) Traceback at creation:
    at trace_pyproxy_alloc (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:3640:23)
    at Object.pyproxy_new (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:3698:34)
    at pyproxy_new_ex (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:2028:23)
    at pyodide.asm.wasm.python2js_inner (wasm://wasm/pyodide.asm.wasm-029d235e:wasm-function[477]:0x1753fe)
    at pyodide.asm.wasm.python2js (wasm://wasm/pyodide.asm.wasm-029d235e:wasm-function[480]:0x175479)
    at pyodide.asm.wasm._pyproxy_iter_next (wasm://wasm/pyodide.asm.wasm-029d235e:wasm-function[444]:0x173d64)
    at Module.__pyproxy_iter_next (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:32251:43)
    at iter_helper (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:4086:23)
    at ht.next (<anonymous>)
    at new Map (<anonymous>)
tuple (3, 4) Traceback at creation:
    at trace_pyproxy_alloc (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:3640:23)
    at Object.pyproxy_new (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:3698:34)
    at pyproxy_new_ex (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:2028:23)
    at pyodide.asm.wasm.python2js_inner (wasm://wasm/pyodide.asm.wasm-029d235e:wasm-function[477]:0x1753fe)
    at pyodide.asm.wasm.python2js (wasm://wasm/pyodide.asm.wasm-029d235e:wasm-function[480]:0x175479)
    at pyodide.asm.wasm._pyproxy_iter_next (wasm://wasm/pyodide.asm.wasm-029d235e:wasm-function[444]:0x173d64)
    at iter_helper (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:4086:23)
    at ht.next (<anonymous>)
    at new Map (<anonymous>)
    at JsvFunction_Construct (/home/rchatham/Documents/programming/pyodide/dist/pyodide.asm.js:2733:40)
```