MAINT Improve handling of fatal startup errors (#3023)
This moves the fatal startup errors into a separate function and added `stderr`
redirection so that the error context can be included in the error message.

The new errors look like:
```
FatalPyodideError: Failed to import _pyodide module
Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/__init__.py", line 20, in <module>
    blah()
  File "/lib/python3.10/_pyodide/__init__.py", line 19, in blah
    f()
  File "/lib/python3.10/_pyodide/__init__.py", line 18, in f
    raise Exception("oops")
Exception: oops
```